server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/storage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  circuitbreaker:
    instances:
      fileStorage:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
  retry:
    instances:
      fileStorage:
        max-attempts: 3
        wait-duration: 1s

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 2000
        read-timeout: 5000

file-storage:
  service:
    url: http://file-storage:8081

wordcloud:
  output:
    dir: /file-analysis/wordclouds